-- Alineación del esquema existente con los modelos Sequelize
-- Ejecutar en la base de datos de Supabase antes de iniciar el backend.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'categoriagasto'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'categoria_gasto'
  ) THEN
    EXECUTE 'ALTER TABLE public."categoriagasto" RENAME TO categoria_gasto';
  END IF;
END
$$ LANGUAGE plpgsql;

----------------------------------------------------------------------
-- Helper para convertir columnas numéricas a INTEGER e identidad
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.ensure_identity(
  p_table TEXT,
  p_column TEXT
) RETURNS VOID AS
$$
DECLARE
  v_full_table TEXT := format('public.%I', p_table);
  v_is_identity TEXT;
  v_data_type TEXT;
BEGIN
  SELECT c.is_identity, c.data_type
  INTO v_is_identity, v_data_type
  FROM information_schema.columns c
  WHERE c.table_schema = 'public'
    AND c.table_name = p_table
    AND c.column_name = p_column;

  IF NOT FOUND THEN
    RAISE NOTICE 'Tabla %.% no encontrada, omitiendo', p_table, p_column;
    RETURN;
  END IF;

  IF v_data_type <> 'integer' THEN
    EXECUTE format(
      'ALTER TABLE %s ALTER COLUMN %I TYPE integer USING %I::integer',
      v_full_table,
      p_column,
      p_column
    );
  END IF;

  IF v_is_identity <> 'YES' THEN
    EXECUTE format(
      'ALTER TABLE %s ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
      v_full_table,
      p_column
    );
  END IF;
END;
$$ LANGUAGE plpgsql;

----------------------------------------------------------------------
-- Aplicar a las tablas principales
----------------------------------------------------------------------
SELECT public.ensure_identity('usuario', 'idusuario');
SELECT public.ensure_identity('rol', 'idrol');
SELECT public.ensure_identity('categoria_gasto', 'idcategoria');
SELECT public.ensure_identity('caja_registradora', 'idcaja');
SELECT public.ensure_identity('caja_fuerte', 'idcajafuerte');
SELECT public.ensure_identity('bitacora_auditoria', 'idbitacora');
SELECT public.ensure_identity('gasto', 'idgasto');
SELECT public.ensure_identity('venta_diaria', 'idventa');
SELECT public.ensure_identity('reporte_diario', 'idreporte');
SELECT public.ensure_identity('conteo', 'idconteo');
SELECT public.ensure_identity('diferencia_caja', 'iddiferencia');
SELECT public.ensure_identity('tipo_conteo', 'idtipoconteo');
SELECT public.ensure_identity('tipo_diferencia', 'idtipodiferencia');

----------------------------------------------------------------------
-- Ajustes de longitud y obligatoriedad para columnas de gasto
----------------------------------------------------------------------
ALTER TABLE public.gasto
  ALTER COLUMN numerocomprobante TYPE varchar(200),
  ALTER COLUMN numerocomprobante SET NOT NULL,
  ALTER COLUMN descripcion SET NOT NULL,
  ALTER COLUMN rutacomprobante TYPE varchar(400);

----------------------------------------------------------------------
-- Crear tabla de tiendas si no existe
----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.store (
  id varchar(100) PRIMARY KEY,
  name varchar(200) NOT NULL,
  code varchar(100) UNIQUE NOT NULL,
  active boolean DEFAULT true NOT NULL
);

----------------------------------------------------------------------
-- Limpiar helper
----------------------------------------------------------------------
DROP FUNCTION public.ensure_identity(TEXT, TEXT);

